/* eslint-disable import/no-anonymous-default-export */
/** @type {import('tailwindcss').Config} */
export default {
    content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
    theme: {
      extend: {
        screens: {
          xs: "320px",
          sm: "640px",
          md: "768px",
          lg: "1024px",
          xl: "1280px",
          "2xl": "1536px",
        },
        fontSize: {
          xs: ["0.75rem", { lineHeight: "1rem" }],
          sm: ["0.875rem", { lineHeight: "1.25rem" }],
          base: ["1rem", { lineHeight: "1.5rem" }],
          lg: ["1.125rem", { lineHeight: "1.75rem" }],
          xl: ["1.25rem", { lineHeight: "1.75rem" }],
          "2xl": ["1.5rem", { lineHeight: "2rem" }],
          "3xl": ["1.875rem", { lineHeight: "2.25rem" }],
          "4xl": ["2.25rem", { lineHeight: "2.5rem" }],
          "5xl": ["3rem", { lineHeight: "1" }],
          "6xl": ["3.75rem", { lineHeight: "1" }],
          "7xl": ["4.5rem", { lineHeight: "1" }],
          "8xl": ["6rem", { lineHeight: "1" }],
          "9xl": ["8rem", { lineHeight: "1" }],
        },
        fontWeight: {
          thin: "100",
          extralight: "200",
          light: "300",
          normal: "400",
          medium: "500",
          semibold: "600",
          bold: "700",
          extrabold: "800",
          black: "900",
        },
        colors: {
          white:{
            DEFAULT: '#fff'
          },
          gray: {
            200: '#D5DAE1',
            500: '#003f26',
          },
          black: {
            DEFAULT: '#000',
            500: '#1D2235',
          },
          blue: {
            500: '#2b77e7',
          },
          orange:{
            500: '#ffa600',
          },
          skyBlue:{
            500: '#3fd89c',
          },
          yellow: {
            500: '#d8ff60',
          },
          purple:{
            500: '#f1c8f1',
          },
          lightBlue:{
            500:'#e5ebe7',
          },
          lightGreen:{
            500: '#c3feac',
          },
          teal:{
            500: '#9b0094',
          },
          darkTeal:{
            500: '#06002f',
          },
          burgendy:{
            500: '#b90c4c',
          }
        },
        fontFamily: {
          worksans: ['Work Sans', 'sans-serif'],
          poppins: ['Poppins', 'sans-serif'],
        },
        boxShadow: {
          card: '0px 1px 2px 0px rgba(0, 0, 0, 0.05)',
        },
        fontSize: {
          xs: ["0.75rem", { lineHeight: "1rem" }],
          sm: ["0.875rem", { lineHeight: "1.25rem" }],
          base: ["1rem", { lineHeight: "1.5rem" }],
          lg: ["1.125rem", { lineHeight: "1.75rem" }],
          xl: ["1.25rem", { lineHeight: "1.75rem" }],
          "2xl": ["1.5rem", { lineHeight: "2rem" }],
          "3xl": ["1.875rem", { lineHeight: "2.25rem" }],
          "4xl": ["2.25rem", { lineHeight: "2.5rem" }],
          "5xl": ["3rem", { lineHeight: "1" }],
          "6xl": ["3.75rem", { lineHeight: "1" }],
          "7xl": ["4.5rem", { lineHeight: "1" }],
          "8xl": ["6rem", { lineHeight: "1" }],
          "9xl": ["8rem", { lineHeight: "1" }],
        },
        flex: {
          1: "1 1 0%",
          auto: "1 1 auto",
          initial: "0 1 auto",
          none: "none",
        },
        flexGrow: {
          0: "0",
          DEFAULT: "1",
        },
        flexShrink: {
          0: "0",
          DEFAULT: "1",
        },
        variants: {
          accessibility: ["responsive", "focus-within", "focus"],
          alignContent: ["responsive"],
          alignItems: ["responsive"],
          alignSelf: ["responsive"],
          animation: ["responsive"],
          appearance: ["responsive"],
          backdropBlur: ["responsive"],
          backdropBrightness: ["responsive"],
          backdropContrast: ["responsive"],
          backdropFilter: ["responsive"],
          backdropGrayscale: ["responsive"],
          backdropHueRotate: ["responsive"],
          backdropInvert: ["responsive"],
          backdropOpacity: ["responsive"],
          backdropSaturate: ["responsive"],
          backdropSepia: ["responsive"],
          backgroundAttachment: ["responsive"],
          backgroundBlendMode: ["responsive"],
          backgroundClip: ["responsive"],
          backgroundColor: [
            "responsive",
            "dark",
            "group-hover",
            "focus-within",
            "hover",
            "focus",
          ],
          backgroundImage: ["responsive"],
          backgroundOpacity: [
            "responsive",
            "dark",
            "group-hover",
            "focus-within",
            "hover",
            "focus",
          ],
          backgroundPosition: ["responsive"],
          backgroundRepeat: ["responsive"],
          backgroundSize: ["responsive"],
          backgroundOrigin: ["responsive"],
          blur: ["responsive"],
          borderCollapse: ["responsive"],
          borderColor: [
            "responsive",
            "dark",
            "group-hover",
            "focus-within",
            "hover",
            "focus",
          ],
          borderOpacity: [
            "responsive",
            "dark",
            "group-hover",
            "focus-within",
            "hover",
            "focus",
          ],
          borderRadius: ["responsive"],
          borderStyle: ["responsive"],
          borderWidth: ["responsive"],
          boxDecorationBreak: ["responsive"],
          boxShadow: ["responsive", "group-hover", "focus-within", "hover", "focus"],
          boxSizing: ["responsive"],
          brightness: ["responsive"],
          clear: ["responsive"],
          container: ["responsive"],
          contrast: ["responsive"],
          cursor: ["responsive"],
          display: ["responsive"],
          divideColor: ["responsive", "dark"],
          divideOpacity: ["responsive", "dark"],
          divideStyle: ["responsive"],
          divideWidth: ["responsive"],
          dropShadow: ["responsive"],
          fill: ["responsive"],
          filter: ["responsive"],
          flex: ["responsive"],
          flexDirection: ["responsive"],
          flexGrow: ["responsive"],
          flexShrink: ["responsive"],
          flexWrap: ["responsive"],
          float: ["responsive"],
          fontFamily: ["responsive"],
          fontSize: ["responsive"],
          fontSmoothing: ["responsive"],
          fontStyle: ["responsive"],
          fontVariantNumeric: ["responsive"],
          fontWeight: ["responsive"],
          gap: ["responsive"],
          gradientColorStops: ["responsive", "dark", "hover", "focus"],
          grayscale: ["responsive"],
          gridAutoColumns: ["responsive"],
          gridAutoFlow: ["responsive"],
          gridAutoRows: ["responsive"],
          gridColumn: ["responsive"],
          gridColumnEnd: ["responsive"],
          gridColumnStart: ["responsive"],
          gridRow: ["responsive"],
          gridRowEnd: ["responsive"],
          gridRowStart: ["responsive"],
          gridTemplateColumns: ["responsive"],
          gridTemplateRows: ["responsive"],
          height: ["responsive"],
          hueRotate: ["responsive"],
          inset: ["responsive"],
          invert: ["responsive"],
          isolation: ["responsive"],
          justifyContent: ["responsive"],
          justifyItems: ["responsive"],
          justifySelf: ["responsive"],
          letterSpacing: ["responsive"],
          lineHeight: ["responsive"],
          listStylePosition: ["responsive"],
          listStyleType: ["responsive"],
          margin: ["responsive"],
          maxHeight: ["responsive"],
          maxWidth: ["responsive"],
          minHeight: ["responsive"],
          minWidth: ["responsive"],
          mixBlendMode: ["responsive"],
          objectFit: ["responsive"],
          objectPosition: ["responsive"],
          opacity: ["responsive", "group-hover", "focus-within", "hover", "focus"],
          order: ["responsive"],
          outline: ["responsive", "focus-within", "focus"],
          overflow: ["responsive"],
          overscrollBehavior: ["responsive"],
          padding: ["responsive"],
          placeContent: ["responsive"],
          placeItems: ["responsive"],
          placeSelf: ["responsive"],
          placeholderColor: ["responsive", "dark", "focus"],
          placeholderOpacity: ["responsive", "dark", "focus"],
          pointerEvents: ["responsive"],
          position: ["responsive"],
          resize: ["responsive"],
          ringColor: ["responsive", "dark", "focus-within", "focus"],
          ringOffsetColor: ["responsive", "dark", "focus-within", "focus"],
          ringOffsetWidth: ["responsive", "focus-within", "focus"],
          ringOpacity: ["responsive", "dark", "focus-within", "focus"],
          ringWidth: ["responsive", "focus-within", "focus"],
          rotate: ["responsive", "hover", "focus"],
          saturate: ["responsive"],
          scale: ["responsive", "hover", "focus"],
          sepia: ["responsive"],
          skew: ["responsive", "hover", "focus"],
          space: ["responsive"],
          stroke: ["responsive"],
          strokeWidth: ["responsive"],
          tableLayout: ["responsive"],
          textAlign: ["responsive"],
          textColor: [
            "responsive",
            "dark",
            "group-hover",
            "focus-within",
            "hover",
            "focus",
          ],
          textDecoration: [
            "responsive",
            "group-hover",
            "focus-within",
            "hover",
            "focus",
          ],
          textOpacity: [
            "responsive",
            "dark",
            "group-hover",
            "focus-within",
            "hover",
            "focus",
          ],
          textOverflow: ["responsive"],
          textTransform: ["responsive"],
          transform: ["responsive"],
          transformOrigin: ["responsive"],
          transitionDelay: ["responsive"],
          transitionDuration: ["responsive"],
          transitionProperty: ["responsive"],
          transitionTimingFunction: ["responsive"],
          translate: ["responsive", "hover", "focus"],
          userSelect: ["responsive"],
          verticalAlign: ["responsive"],
          visibility: ["responsive"],
          whitespace: ["responsive"],
          width: ["responsive"],
          wordBreak: ["responsive"],
          zIndex: ["responsive", "focus-within", "focus"],
        },
      },
    },
    plugins: [],
  };
  